[terminal]
shell = "/bin/zsh"
[window]
startup_mode = "Windowed"
dynamic_title = false
title = "Shell"
decorations_theme_variant = "Dark"
[font]
size = 16
normal = { family = "JetBrainsMono NF", style = "Medium" }
[selection]
save_to_clipboard = true
[mouse]
hide_when_typing = true
[cursor]
style = { blinking = "On" }
[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "F2", action = "CreateNewWindow" },
]
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'
