[window]
startup_mode = "Windowed"
dynamic_title = false
title = ""
decorations_theme_variant = "Dark"
[font]
size = 14
normal = { family="JetBrains Mono",style="Medium" }
[selection]
save_to_clipboard = true
[mouse]
hide_when_typing = true
[cursor]
style = { blinking = "On" }
[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
{ key = "F2", action = "CreateNewWindow" },
]
